version: '3.1'
services:
  odoo:
    build: ./17.0
    ports:
      - "8069:8069"
    environment:
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
